# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53aa6b2001a9dbf5a7167900b9034fedbad6ef53c2a78596bc3ec67b8d8f355f7176a5cc6775ba3a5f0edfafa697afce0ec0bf68ee57c0049533fa8a8c130852

test:
  secret_key_base: 87dab3a41815fb46c2957ab184d16b10cebbe51671c4dce3d3b02e9a06dfc96f4c51b4a3746d3f41168370f1614fc98a6614cfd282b7fc220080bcaad31868ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
